### チケット作成
POST http://localhost:3001/tickets
Content-Type: application/json

{
  "title": "テストチケット",
  "description": "これはテスト用の説明です"
}

### チケットクローズ
DELETE http://localhost:3001/tickets/ba9fc562-49d3-4cb0-8e79-241119051f8a
