### チケット作成
POST http://localhost:3000/tickets
Content-Type: application/json

{
  "title": "テストチケット",
  "description": "これはテスト用の説明です"
}

### チケットクローズ
DELETE http://localhost:3000/tickets/48664659-faa6-48a5-bb3f-d622ace632bf
